# Generated by Django 2.0.3 on 2018-05-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='description',
        ),
    ]
