# Generated by Django 2.0.3 on 2018-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('created_by', models.CharField(max_length=128)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
