# Generated by Django 2.0.3 on 2018-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0001_initial'),
        ('profiles', '0002_auto_20180505_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highlight',
            field=models.ManyToManyField(blank=True, related_name='profile', to='highlight.Highlight'),
        ),
    ]
